/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int btn_save=0x7f020000;
        public static final int btn_scan=0x7f020001;
        public static final int btn_toggle=0x7f020002;
        public static final int btn_toggle_bg=0x7f020003;
        public static final int icon=0x7f020004;
        public static final int mainbackground=0x7f020005;
        public static final int off=0x7f020006;
        public static final int on=0x7f020007;
        public static final int save_disabled=0x7f020008;
        public static final int save_normal=0x7f020009;
        public static final int save_press=0x7f02000a;
        public static final int scan_disabled=0x7f02000b;
        public static final int scan_normal=0x7f02000c;
        public static final int scan_press=0x7f02000d;
    }
    public static final class id {
        public static final int addLabelText=0x7f060006;
        public static final int autoscan=0x7f060004;
        public static final int labelName=0x7f060003;
        public static final int onoff=0x7f060001;
        public static final int saveButton=0x7f060007;
        public static final int scan=0x7f060005;
        public static final int scrollView1=0x7f060008;
        public static final int textStatus=0x7f060009;
        public static final int textView1=0x7f060000;
        public static final int wifistate=0x7f060002;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int Scan_button=0x7f040004;
        public static final int addlabeledittext=0x7f040007;
        public static final int app_name=0x7f040000;
        public static final int autoscan=0x7f040005;
        public static final int program_title=0x7f040003;
        public static final int save_label=0x7f040006;
        public static final int scan_wifi=0x7f040002;
        public static final int switch_wifi=0x7f040001;
    }
    public static final class style {
        /**  Perhaps more theme items here...? 
         */
        public static final int ToggleButtonTheme=0x7f050001;
        /**  Overwrite the ToggleButton style 
         */
        public static final int Widget_Button_Toggle=0x7f050000;
    }
}
